apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-spotify
  labels:
    {{- include "orpheus.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPOTIFY_CLIENT_ID: {{ .Values.spotify.clientId | quote }}
  SPOTIFY_CLIENT_SECRET: {{ .Values.spotify.clientSecret | quote }}
  SPOTIFY_REDIRECT_URI: {{ include "orpheus.spotify.redirectUri" . | quote }}
